Added the ability to have absolute Paths
rupurt/webpack-copy-after-build-plugin pull request #1
Opened 2017-04-25 22:13 UTC by benwestrate

Created an options object containing an attribute `absoluteMappingPaths` which when set to true the plugin will now assume that you are giving it the absolute path to the destination. This gives the plugin a bit more flexibility.

2017-04-25 22:57 UTC, rupurt requested changes

2017-04-25 22:57 UTC, rupurt commented on index.js
> +        if( options.absoluteMappingPaths === true ){
How do you feel about using truthyness here and only assigning the other `to` in the `else` condition? i.e.

```javascript
var to;

if (options.absoluteMappingPaths) {
   to = mapping;
} else {
   to = outputPath + "/" + mapping;
}
```

2017-04-25 22:57 UTC, rupurt commented
Hey @benwestrate,

Thanks for the PR! I added a minor comment.

2017-04-26 13:00 UTC, benwestrate commented on index.js
> +        if( options.absoluteMappingPaths === true ){
sure sounds good ill make the change

2017-04-26 13:12 UTC, benwestrate commented on index.js
> +        if( options.absoluteMappingPaths === true ){
Ok, change made. Let me know if there is anything else that stands out.

2017-04-26 16:23 UTC, merged

2017-04-26 16:25 UTC, rupurt commented on index.js
> +        if( options.absoluteMappingPaths === true ){
Sweet. Thanks @benwestrate

2017-04-26 18:05 UTC, benwestrate commented
@rupurt could you also publish this back to npm? thanks!